name = IAM
description = Structure based on 2 column header 2/3 column main and 1 col sidebar only on wide screen
preview = preview.png
template = IAM-layout

;Regions
regions[branding] = Branding
regions[header_first] = Header First
regions[header_second] = Header Second
regions[navigation] = Navigation
regions[preface_first] = Preface First
regions[preface_second] = Preface Second
regions[preface_third] = Preface Third
regions[highlighted] = Highlighted
regions[help] = Help
regions[content] = Content
regions[sidebar_first] = First Sidebar
regions[sidebar_second] = Second Sidebar
regions[midsection] = Midsection
regions[postscript_first] = Postscript First
regions[postscript_second] = Postscript Second
regions[postscript_third] = Postscript Third
regions[footer] = Footer

;Styles
stylesheets[all][]=css/layouts/IAM/iam.IAM.layout.css
stylesheets[all][]=css/layouts/IAM/IAM.layout.css
stylesheets[all][]=css/layouts/IAM/IAM.layout.no-query.css